apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./patchs/deployment-patch.yaml
- ./patchs/service-patch.yaml

namespace: argocd-poc-dev

images:
- name: argocd-poc
  newName: vgalvaom/argocd-poc
  newTag: c4c4f841eb4163392d0a24f1511dd8da1599e7c0
resources:
- ../base
