apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patchesStrategicMerge:
- service-patch.yml

namespace: argocd-poc-dev

images:
- name: argocd-poc
  newName: vgalvaom/argocd-poc
  newTag: ca0570934b2c805d0080ec6ce41a28aef67890c4
