apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- service.yml
- ../base

namespace: app-argocd-poc-dev

images:
- name: argocd-poc
  newName: vgalvaom/argocd-poc
  newTag: 892b7be05206c77d17b34f537395c8ed050bd9b2
