apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- service.yml
- configmap.yml
- ../base

namespace: app-argocd-poc-dev

images:
- name: argocd-poc
  newName: vgalvaom/argocd-poc
  newTag: 87e506cfdbbc927ea5c3a844729284d6d88e0597
