apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollouts-demo-deployment.yaml
- rollouts-demo-service.yaml

namespace: default

images:
- name: rollouts-demo
  newName: argoproj/rollouts-demo
  newTag: blue
