apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-service
spec:
  type: NodePort
  selector:
    app: rollouts-demo
  ports:     
    - port: 8080
      targetPort: 8080
      nodePort: 30007
