apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- service.yml
- ../base

namespace: argocd-poc

images:
- name: argocd-poc
  newName: vgalvaom/argocd-poc
  newTag: 12d83a95da2e529be6175086f7406750b61b562f
