apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- service.yml
- configmap.yml
- ../base

namespace: app-argocd-poc-prod

images:
- name: argocd-poc
  newName: vgalvaom/argocd-poc
  newTag: 051d1443219f1590c48085a640f71399a2dcb9c7
