apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- service.yml
- ../base

namespace: argocd-poc

images:
- name: argocd-poc
  newName: vgalvaom/argocd-poc
  newTag: 12e10900122147022b2260e77d6fab4600ca271f
