apiVersion: v1
kind: Service
metadata:
  name: argocd-poc-srv
spec:
  type: NodePort
  selector:
    app: argocd-poc
  ports:
  - port: 8081
    name: port-prod
    targetPort: 8181
    nodePort: 30001
