apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: argocd-poc

images:
- name: argocd-poc
  newName: vgalvaom/argocd-poc
  newTag: 69b8094563c5712125995f96498655ffd18967c1
